version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashopdb
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    ports:
      - 3306:3306
    volumes:
      - ./maria_db_data:/var/lib/mysql

  memcache:
    build: cache_bd
    ports:
      - 11211:11211

  web:
    build: servidor_web
    ports:
      - 80:80
